{
  "pr_checks": {
    "approvals": [
      {
        "check_name" : "Content team approval",
        "teams" : [],
        "users" : ["jeffposnick"],
        "paths" : [
          "site/_data/i18n/*"
        ]
      },
      {
        "check_name" : "Eng team approval",
        "teams" : [],
        "users" : ["jeffposnick"],
        "paths" : [
          "**/*.js",
          "**/*.njk"
        ]
      }
    ]
  }
}
