version: 1
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 1
        must_include:
                  regex: 'site/content/*'
        limit:
          teams: [ '@GoogleChrome/web-dev-eng', 'devnook' ]

