# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist/"
  command = "npm run production"
  # Don't build NaCl docs during Netlify preview builds.
  # These take forever and we don't need them for PR previews.
  environment = { CI = "true", ELEVENTY_IGNORE_NACL = "true" }

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 200
