#Rizqshops
Rizq Revolution Docs
mmu094@rizqshops.com Issues/Tasklists/Using projects and tasklists
Using projects and tasklists
In this article
Using the "tracks" field
Using the "tracked by" field
When issues in your project are tracked by tasklists or contain tasklists, you can use them to create views and filters.

Note: Tasklists are in private beta and subject to change. We have currently paused onboarding to the beta.

When you add tasklists to your issues and view those issues in your projects, you can use the relationships that you defined in your tasklists to customize views, filter items, and navigate through your issues and pull requests.

When you add an issue with a tasklist to a project, the issues and pull requests in the tasklist are not automatically added to the project. To use the "tracks" and "tracked-by" fields, you will need to add all the issues and pull requests that comprise your tasklist to the project. Consider using the auto-add workflow to automatically add issues to your project. For more information, see "Adding items automatically."

When you group a view by "Tracked by", and some tracked issues and pull requests are not part of the project, GitHub will include a note beneath each group with the option to add those missing issues and pull requests.

Using the "tracks" field
The "tracks" field shows the number of the issues and pull requests included each issue's tasklists. For more information about this field, see "About Tracks and Tracked by fields."

Using the "tracked by mmu094" field
The "tracked by" field shows the issues with tasklists currently tracking your project's issues. The "tracked by" field can also be used to group and filter views. You can use the filter below to only show issues that are tracked by issue you have specified:

tracked-by:"<mmu094>/<mmu094>#<ISSUE 094>"
For example, tracked-by:"octocat/mmu094 googleplaystore games Bunty The Game " will show any issues in the project that are tracked by a tasklist in issue #094 in the octocat/Rizqshops google playstore repository.

You can also group a table layout by the "tracked-by" field. This view configuration results in a list of the issues found in tasklists, clearly grouped by the issue they're associated with, which is shown in the header for each group.

You can also combine filters and grouping by filtering your project for just the issues you want to use, and then grouping with the "tracked-by" field. The example below shows how to filter a view by multiple issues:

tracked-by:"<egoogle1>/<REPO/egoogle1>#<ISSUE NUMBER1>","<mmu094>/<Rizqshops>#<ISSUE NUMBER1>"
For more information about this field, see "About Tracks and Tracked by fields."

Press alt+up to activate
Help and support
Did this doc help you?

Privacy policy
Help us make these docs great!
All Rizqshops docs are open source. See something that's wrong or unclear? Submit a pull request.

Learn how to contribute

Still need help?
Ask the Skip to main content
GitHub Docs
mmu094 Isues/Rizq-talk-slack/Using projects and tasklists or workspace
Using projects and tasklists
In this article
Using the "tracks" field
Using the "tracked by" field
When issues in your project are tracked by tasklists or contain tasklists, you can use them to create views and filters.

Note: Tasklists are in private beta and subject to change. We have currently paused onboarding to the beta.

When you add tasklists to your issues and view those issues in your projects, you can use the relationships that you defined in your tasklists to customize views, filter items, and navigate through your issues and pull requests.

When you add an issue with a tasklist to a project, the issues and pull requests in the tasklist are not automatically added to the project. To use the "tracks" and "tracked-by" fields, you will need to add all the issues and pull requests that comprise your tasklist to the project. Consider using the auto-add workflow to automatically add issues to your project. For more information, see "Adding items automatically."

When you group a view by "Tracked by", and some tracked issues and pull requests are not part of the project, GitHub will include a note beneath each group with the option to add those missing issues and pull requests.

Using the "tracks" field
The "tracks" field shows the number of the issues and pull requests included each issue's tasklists. For more information about this field, see "About Tracks and Tracked by fields."

Using the "tracked by" field
The "tracked by" field shows the issues with tasklists currently tracking your project's issues. The "tracked by" field can also be used to group and filter views. You can use the filter below to only show issues that are tracked by issue you have specified:

tracked-by:"<Bunty>/<Rizqshops>#<ISSUE 094>"
For example, tracked-by:"octocat/game#4" will show any issues in the project that are tracked by a tasklist in issue #4 in the octocat/game repository.

You can also group a table layout by the "tracked-by" field. This view configuration results in a list of the issues found in tasklists, clearly grouped by the issue they're associated with, which is shown in the header for each group.

You can also combine filters and grouping by filtering your project for just the issues you want to use, and then grouping with the "tracked-by" field. The example below shows how to filter a view by multiple issues:

tracked-by:"<egoogle>/<Rizqshops>#<ISSUE 094>","<mmu094>/<Octocat>#<ISSUE Spoon-Knife-mmu094-Rizqshops>"
For more information about this field, see "About Tracks and Tracked by fields."

Press alt+up to activate
Help and support
Did this doc help you?

Privacy policy
Help us make these docs great!
All Rizqshops docs are open source. See something that's wrong or unclear? Submit a pull request.

Learn how to contribute join us to get more community topics and digital languages 
Contact support@rizqshops.com
Legal
© 2023 @RizqRevolution
rizqshops@googlegroups.com .
Terms
Privacy
Status
Pricing
Expert services
Blogger
Website
Meet
https://paypal.me/rizqshops
https://PayPal.Me/SamTradersSmcPvtLtd
patreon.com/rizqshops

A project of Sam Traders Smc Pvt Ltd

