/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const assert = require('assert');
const typedoc = require('typedoc');
const typedocModels = require('typedoc/dist/lib/models');
const htmlEscaper = require('html-escaper');

/**
 * @param {typedoc.DeclarationReflection} reflection
 * @param {typedoc.ReflectionKind=} kindMask
 * @return {{[name: string]: typedoc.DeclarationReflection}}
 */
function exportedChildren(reflection, kindMask = 0) {
  /** @type {{[name: string]: typedoc.DeclarationReflection}} */
  const all = {};

  for (let cand of reflection.children ?? []) {
    if (!cand.flags.hasFlag(typedoc.ReflectionFlag.Exported)) {
      continue;
    }
    const {name} = cand;

    if (cand.kind === typedoc.ReflectionKind.Reference) {
      const reference = /** @type {typedoc.ReferenceReflection} */ (cand);
      const target = reference.getTargetReflection();
      if (!(target instanceof typedocModels.DeclarationReflection)) {
        continue;
      }
      cand = target;
    }

    if (!(cand.kind & kindMask)) {
      continue;
    }
    all[name] = cand;
  }

  return all;
}

/**
 * @param {typedocModels.Comment|undefined} comment
 * @return {string}
 */
function extractComment(comment) {
  const out = (comment?.shortText ?? '') + (comment?.text ?? '');
  return ensureCommentSafeHTML(out);
}

/**
 * Wraps the passed comment in HTML. Basically ensures the comment is comprised
 * of top-level tags.
 *
 * @param {string} out
 * @return {string}
 */
function ensureCommentSafeHTML(out) {
  out = out.trim();
  if (!out) {
    return '';
  }

  // No paragraph wrapper, include one and return.
  if (!out.includes('<p>')) {
    return `<p>${out}</p>`;
  }

  // Already wrapped in a paragraph. Return.
  if (out.startsWith('<p>') && out.endsWith('</p>')) {
    return out;
  }

  // This is a comment which looks like, and is regularly generated by TS:
  //
  //    Hello, I am some long-form content!
  //    <p>For some reason there's a trailing paragraph!</p>
  //    <pre>/* often a code block here too */</pre>
  //
  // We put the first part in a paragraph.
  if (/<\/\w+>$/.test(out)) {
    const indexOfParagraph = out.indexOf('<p>');
    const initialPart = out.substr(0, indexOfParagraph);
    const restPart = out.substr(indexOfParagraph);
    return `<p>${initialPart}</p>\n${restPart}`;
  }

  // Works around specific issue.
  if (out.endsWith('<p>')) {
    out = out.substr(0, out.length - 3);
    return ensureCommentSafeHTML(out);
  }

  // Drop all HTML entities from this. This only happens in one case where
  // inline HTML is used to demonstrate an example.
  out = htmlEscaper.escape(out);
  return ensureCommentSafeHTML(out);
}

/**
 * @param {RenderType|undefined} a
 * @param {RenderType|undefined} b
 * @return {boolean}
 */
function deepStrictEqual(a, b) {
  try {
    // @ts-ignore
    assert.deepStrictEqual(a, b);
  } catch (e) {
    return false;
  }
  return true;
}

module.exports = {
  exportedChildren,
  extractComment,
  deepStrictEqual,
};
