timeout: 2700s # set build timeout to 45 mins
steps:
  - name: node:18
    entrypoint: npm
    args: ['ci', '--no-audit', '--omit=optional']

  - name: node:18
    entrypoint: npm
    args: ['run', 'production']
    env:
      - 'NODE_OPTIONS="--max_old_space_size=8192"' # https://github.com/GoogleChrome/developer.chrome.com/issues/2439
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -rf dist/en/* dist/ &&
        rm -rf dist/en &&
        gcloud storage cp -L manifest.csv -j html,xml,css,js --recursive dist gs://static-dcc-staging/$SHORT_SHA &&
        gcloud storage cp manifest.csv gs://static-dcc-staging/$SHORT_SHA/manifest.csv &&
        echo $SHORT_SHA > activeCommit.txt &&
        gcloud storage cp activeCommit.txt gs://static-dcc-staging/activeCommit.txt
options:
  machineType: 'E2_HIGHCPU_32'