steps:
  - name: google/cloud-sdk
    args:
      - '-c'
      - |
        set -eou pipefail
        shopt -s inherit_errexit

        echo "Triggering build for ${COMMIT_SHA}"
        gcloud alpha builds triggers run ${_TRIGGER_NAME} --sha ${COMMIT_SHA}
    waitFor:
      - '-'
    entrypoint: bash
