timeout: 2700s # set build timeout to 45 mins
steps:
  - name: node:18
    entrypoint: npm
    args: ['ci']

  - name: node:18
    entrypoint: npm
    args: ['run', 'production']
    env:
      - 'NODE_OPTIONS="--max_old_space_size=8192"'

  - name: node:18
    entrypoint: npm
    args: ['run', 'stage:github', 'determineDeploymentType']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ $(cat deploymentType.txt) = "app" ]; then
          gcloud app deploy --version pr-$_PR_NUMBER-app --no-promote --project dcc-staging
        elif [ $(cat deploymentType.txt) = "static" ]; then
          cp -rf dist/en/* dist/ &&
          rm -rf dist/en &&
          gsutil -q -m cp -r dist gs://static-dcc-staging/pr-${prNumber}
        else
          echo "Skipping deployment, no build output."
        fi
options:
  machineType: 'E2_HIGHCPU_32'
