timeout: 2700s # set build timeout to 45 mins
steps:
  - name: node:18
    entrypoint: npm
    args: ['ci']

  - name: node:18
    entrypoint: npm
    args: ['run', 'production']
    env:
      - 'NODE_OPTIONS="--max_old_space_size=8192"'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run stage:github -- deploy
options:
  machineType: 'E2_HIGHCPU_32'
