---
name: 'Check'

Trust Wallet
Privacy and Policy
Last Updated: Apr 8, 2022

This Privacy Notice describes the policies and procedures of DApps Platform, Inc., (“we,” “our,” or “us”) pertaining to the collection, use, and disclosure of your information on www.trustwallet.com and related mobile applications and products we offer (the “Services” or “Trust Wallet”).
This Privacy Notice describes the policies and procedures of DApps Platform, Inc., (“we,” “our,” or “us”) pertaining to the collection, use, and disclosure of your information on www.trustwallet.com and related mobile applications and products we offer (the “Services” or “Trust Wallet”).

Overview
Your right to privacy and the protection of your personal data is important to us. The following sections provide further details as to how we process your personal information through Trust Wallet. We don’t share your information with third parties except to deliver you our Services and products, comply with the law, make Trust Wallet better, protect our rights, or effectuate a business transfer. We’re not a huge, faceless corporation. We’re just developers trying to deliver an incredible product. If you have any questions or concerns about this policy, please reach out to us at support@trustwallet.com.

How do you accept this policy
By using Trust Wallet, including downloading one of our mobile applications or visiting our website, you agree to the use, disclosure, and procedures outlined in this Privacy Policy.

What personal information do we collect from our users
We do our best to minimize the amount of Personal Information that we collect from Trust Wallet users. Your contact information, such as your phone number,, or email address (depending on how you contact us), may be collected when you communicate with us for support, or if you report a bug or other error related to Trust Wallet or when you interact with us through social media. When you use our Services, we process PUBLIC wallet addresses that you generate through Trust Wallet.

Will we share your personal date with third parties
Information about our users is an important part of our business and we are not in the business of selling our users’ personal information to others. We may transfer personal data to our service providers or third parties in connection with Trust Wallet’s operation of its business, as certain features on Trust Wallet rely on various third-party products and services (collectively “Third Party Services”), . These third party services providers only have access to certain Personal Information, such as your public Wallet addresses, to perform their functions and may not use it for other purposes. Furthermore, they must process the personal information in accordance with our contractual agreements and only as permitted by applicable data protections laws. Business transfers: As we continue to develop our business, we might sell or buy other businesses or services. In such transactions, user information generally is one of the transferred business assets but remains subject to the promises made in any pre-existing Privacy notice (unless, of course, the user consents otherwise). Also, in the unlikely event that TrustWallet or substantially all of its assets are acquired, users’ information will be one of the transferred assets. We may share non-personally identifiable information publicly and with our partners- like publishers, advertisers, developers, or right holders.

How we use the information we gather
We primarily use the limited information that we collect to enhance Trust Wallet. Except if we sell all or a portion of our business, or as otherwise described below, we do not rent, trade, or sell your Personal Information. Some ways we may use your Personal Information are to: Contact you when necessary; Respond to your comments, questions, or issues related to bugs or errors with Trust Wallet; Provide you with additional information; Send you information and marketing materials about services and products available through Trust Wallet, using push notifications or other means; Train our team members; Other internal business purposes. Aggregated Personal Data and Non-Personal Information We may share or disclose aggregated Personal Data or Non-Personal Information with service providers or with other persons we conduct business with, including but not limited potential third-parties for the purpose of showcasing the performance of the company. These service providers and other persons may also share with us aggregated Non-Personal Information that they have independently developed or acquired. Additionally, we may combine aggregate information from the pixel tags, and web beacons, with similar data we collect from other visitors to help us improve our Services. When doing so, we do our best to ensure that aggregated information cannot be linked back to you. Agents or Third Party Partners We may provide your Personal Information to our employees, contractors, agents, service providers, and designees (“Agents”) to enable them to perform certain services for us, including improvement of website-related services and features, and performance of maintenance services. Business Transfers We may choose to buy or sell assets. In these types of transactions, customer information is typically one of the business assets that would be transferred. Also, if we (or our assets) are acquired, or if we go out of business, enter bankruptcy, or go through some other change of control, your Personal Information could be one of the assets transferred to or acquired by a third party. By accepting this Privacy Notice, as outlined above, you consent to any such transfer. Protection of Us and Others We will share personal information outside of Trust Wallet if we have a reasonable belief that access, use, preservation, or disclosure of the information is reasonably necessary to comply with any applicable law, regulation, legal process, or enforceable governmental request; to cooperate with law enforcement; to enforce or apply our Terms of Use and other agreements; or to protect the rights, property, or safety of Trust Wallet, our employees, our users, or others.

Your rights with respect to the processing of personal data
You are entitled (under the conditions, and subject to the exceptions, set out in applicable law) to: Request Access to the personal information we process about you: You can request access to the information we have collected from you. You can do this by contacting us at support@trustwallet.com. We will provide you with a copy of the data we process about you. To comply with your request, we may ask you to verify your identity. We will fulfill your request by sending your copy electronically. For any subsequent access request, we may charge you an administrative fee. Request a rectification of your personal data: If you believe that the information we have collected is incorrect or incomplete, you may contact us so we can update it and keep your data accurate. Object to the processing of your personal data: you may request that we no longer process your personal data. Request to erase your personal data: you may request the erasure of your personal data, including where such personal data would no longer be necessary to achieve the purposes for which it was collected. Any data that is no longer needed for purposes specified in the “How We Use the Information We Gather” section will be deleted after ninety (90) days. Wallet addresses created through the Trust Wallet application cannot be deleted from the Ethereum blockchain, therefore we are unable to delete this personal information. If at any point you wish for Trust Wallet to delete information about you, you may contact us at support@trustwallet.com. Request the restriction of the processing of your personal data: you may request that TrustWallet only processes your personal data in limited circumstances, including with your consent. Under California Consumer Protection Act (“CCPA”) you also have the right not to be discriminated against because of the exercise of your rights. Please note that we do not sell your personal data.

Data retention
Please note that even If you delete your Wallet or addresses from the Trust Wallet mobile application, uninstall Trust Wallet mobile applications from your device, or request that your information be deleted, we still may retain some information that you have provided to us to maintain Trust Wallet or to comply with the laws and regulations to which Trust Wallet is subject. If you have any question or objection as to how we collect and process your personal information, please contact support@trustwallet.com.

Data security
We are committed to making sure your information is protected in accordance with applicable laws and our data privacy policies. We have selected third-party vendors that use the Ethereum network, including Coinbase, Shapeshift, and Changelly, that help us keep your Personal Information safe. Unfortunately, we do not control these third parties and therefore cannot guarantee complete security. We work to protect the security of your personal information during transmission by using encryption protocols and software. We maintain physical, electronic and procedural safeguards in connection with the collection, storage and disclosure of your personal information and secure all connections with industry standard transport layer security. Even with all these precautions, we cannot fully guarantee against the access, disclosure, alteration, or deletion of data through events, including but not limited to hardware or software failure or unauthorized use. Any information that you provide to us is done so entirely at your own risk.

Children
We are especially sensitive about children’s information. Our Services are not targeted towards children, and our users must be at least eighteen (18) years old to use our services. We don’t knowingly collect information from children under the age of 13. If you are a parent or legal guardian of a minor child, we will treat any information that you provide us while using Trust Wallet on behalf of your minor child as Personal Information as otherwise provided in this Privacy Policy. If you have questions concerning our information practices with respect to children, or if you learn that a child under the age of 13 has used Trust Wallet, created a user account, or provided us with personal information, please email us at support@trustwallet.com

Conditions of use, notices, changes and updates to privacy notice
If you choose to use TrustWallet, your use and any dispute over privacy is subject to this Notice and our Terms of Use. If you have any concerns about privacy at Trust Wallet, please contact us with a complete description, and we will try to resolve it. You also have the right to contact your local Data Protection Authority. We reserve the right to update and revise this Privacy Nolicy at any time. We occasionally review this Privacy Notice to make sure it complies with applicable laws and conforms to changes in our business. If we do revise this Privacy Notice, we will update the “Effective Date” at the top of this page so that you can tell if it has changed since your last visit and will do our best to notify you. Please review this Privacy Notice regularly to ensure that you are aware of its terms. Any use of Trust Wallet after an amendment to our Privacy Notice constitutes your acceptance to the revised or amended terms.

Questions
We’d be happy to answer them. Shoot us an email or send us a note:

Email: support@trustwallet.com

Mailing Address: DApps Platform, Inc. 2810 N Church St, PMB 96630 Wilmington, Delaware 19802 US

Simple and convenient to use, seamless to explore
Download Trust Wallet
Stay Connected:
Wallet
Mobile App
Browser Extension
Features
Buy Crypto
Swaps
Staking
NFTs
Security
Build
Developer Docs
Wallet Core
Submit dApp
Get assets listed
Support
FAQ
Community Forum
Contact Us
About
About Us
Careers
Press Kit
Terms of Service
Privacy Policy
Blog


on: pull_request

jobs:
  queue:
    runs-on: ubuntu-latest
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'outdated_runs'
          cancel_others: true
          skip_after_successful_duplicate: true
          do_not_skip: '["workflow_dispatch", "schedule"]'
  lint:
    needs: queue
    runs-on: ubuntu-latest
    steps:
      - name: Getting changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            js:
              - '**/*.js'
              - '**/*.ts'
              - '**/*.d.ts'
              - '**/*.json'
            md:
              - '**/*.md'
            scss:
              - '**/*.scss'

      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: Installing Node.js packages
        run: npm ci

      - name: Linting JavaScript
        if: ${{ steps.changes.outputs.js == 'true' }}
        run: |
          npm run lint:js
          npm run lint:types

      - name: Linting Markdown
        if: ${{ steps.changes.outputs.md == 'true' }}
        run: npm run lint:md

      - name: Linting SCSS
        if: ${{ steps.changes.outputs.scss == 'true' }}
        run: npm run lint:scss

  test:
    needs: queue
    runs-on: ubuntu-latest
    steps:
      - name: Getting changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            js:
              - 'package.json'
              - 'site/**/*.js'
              - 'server/**.js'
              - 'tests/**.js'

      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: Installing Node.js packages
        run: npm ci

      - name: Running tests
        if: ${{ steps.changes.outputs.js == 'true' }}
        run: |
          npm run test

  build:
    needs: queue
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: Installing Node.js packages
        run: npm ci

      - name: Building site
        env:
          # Increase memory limit as a full build requires around 8GB
          NODE_OPTIONS: --max_old_space_size=8192
          ELEVENTY_INCLUDE_TRANSLATED: true
        run: |
          npm run production

      - name: Packing up built files
        run: |
          tar cfj dist.tar.gz ./dist

      - name: Storing build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ github.run_id }}
          path: dist.tar.gz
          if-no-files-found: error

  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Getting changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'package.json'
              - 'site/_js/**/*.js'
              - 'site/_includes/**/*.njk'
              - 'site/_scss/**/*.scss'

      - name: Cloning repository
        uses: actions/checkout@v3
        if: ${{ steps.changes.outputs.frontend == 'true' }}

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        with:
          cache: npm
          node-version: 16

      - name: Installing Node.js packages
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        run: npm ci

      - name: Downloading build artifacts
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ github.run_id }}

      - name: Unpacking built files
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        run: |
          tar xf dist.tar.gz

      - name: Lighthouse
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        run: |
          npx lhci autorun \
          --config=./lighthouserc.js

  percy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Getting changes
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'package.json'
              - 'site/_filters/**.js'
              - 'site/_includes/**'
              - 'site/_js/**.js'
              - 'site/_plugins/**.js'
              - 'site/_scss/**.scss'
              - 'site/_shortcodes/**.js'
              - 'site/_transforms/**.js'
              - 'site/_utils/**.js'
              - 'site/en/content-types/**'

      - name: Cloning repository
        uses: actions/checkout@v3
        if: ${{ steps.changes.outputs.frontend == 'true' }}

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        with:
          cache: npm
          node-version: 16

      - name: Installing Node.js packages
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        run: npm ci

      - name: Downloading build artifacts
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ github.run_id }}

      - name: Unpacking built files
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        run: |
          tar xf dist.tar.gz

      - name: Percy
        if: ${{ steps.changes.outputs.frontend == 'true' }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npm run snapshots
