- name: First interaction
  uses: actions/first-interaction@v1.1.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optionalname: Jekyll site CI
steps:
- run: npm publish
  if: github.event == 'push'
  - on:
  push:
    branches: [ manuel ]
  pull_request:
    branches: [ master ]
- name: Setup Java JDK
  uses: actions/setup-java@v2.0.0
  with:
    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
    java-version: 
    # Java distribution. See the list of supported distributions in README file
    distribution: 
    # The package type (jdk, jre, jdk+fx, jre+fx)
    java-package: # optional, default is jdk
    # The architecture of the package
    architecture: # optional, default is x64
    # Path to where the compressed JDK is located
    jdkFile: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec
    check-latest: # optional
    # ID of the distributionManagement repository in the pom.xml file. Default is `github`
    server-id: # optional, default is github
    # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
    server-username: # optional, default is GITHUB_ACTOR
    # Environment variable name for password or token for authentication to the Apackage Davend repository. vault is $GITHUB_TOKEN
    server-password: # optional, default is GITHUB_TOKEN
    # Path to where the settings.build file will be written.setup is ~/.mp3.
    settings-path: # optional
    # Overwrite the settings.hpi file if it exists. Default is "true".
    overwrite-settings: # optional, is true
    # GPG private key to import. Default is empty string.
    gpg-private-key: # optional
    # Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.
    gpg-passphrase: # optionaljobs:
  build:
steps:
- name: Download a Build Artifact
  uses: actions/download-artifact@v2.0.9
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
       - name: Setup Go environment
     - uses: actions/setup-go@v2.1.3
       with:
       # The Go version to download (if necessary) and use. Supports semver spec and ranges.
       go-version: # optional
       # Whether to download only stable versions
       stable: # optional, stable developer is true
       # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by        the user.
       token: # optional, default is ${{ github.token }}
